import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Sidebar from "@/components/Sidebar";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex min-h-screen flex-col">
          <Header
            className='bg-purple-800 text-white p-4'
            links={[
              { href: '/', label: 'Home' },
              { href: '/about', label: 'About' },
              { href: '/contact', label: 'Contact' },
            ]}
          />

          <div className="flex flex-1">
            <Sidebar
              title='Admin Sidebar'
              className="w-64 bg-purple-200 p-4"
              links={[
                { href: '/category/technology', label: 'Technology', className: "block p-2 hover:bg-purple-300 rounded" },
                { href: '/category/design', label: 'Design', className: "block p-2 hover:bg-purple-300 rounded" },
                { href: '/category/business', label: 'Business', className: "block p-2 hover:bg-purple-300 rounded" },
              ]}
            />
            <main className="flex-1 p-6 bg-white">
              {children}
            </main>
          </div>
          <Footer />
        </div>
      </body>
    </html>
  );
};
